# Generated by Django 2.1.4 on 2018-12-09 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2018, 12, 9, 19, 40, 6, 864664, tzinfo=utc))),
            ],
        ),
    ]
