# Generated by Django 2.1.4 on 2018-12-09 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 9, 20, 3, 42, 47190, tzinfo=utc), null=True),
        ),
    ]
